/*
 * Copyright (C) 2016 spudrucket
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package spudrucket.github.io.Colloquium;

import spudrucket.github.io.Colloquium.exceptions.IllegalOrphanException;
import spudrucket.github.io.Colloquium.exceptions.NonexistentEntityException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author spudrucket
 */
public class ShowInterviews extends javax.swing.JFrame {
    
    public static int idColumn = 0;
    MainWindow mainwindow;

    /**
     * Creates new form ShowInterviews
     */
    public ShowInterviews() {
        initComponents();
    }
    
    public ShowInterviews(MainWindow mw) {
        this.mainwindow = mw;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ColloquiumPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ColloquiumPU").createEntityManager();
        interviewsQuery = java.beans.Beans.isDesignTime() ? null : ColloquiumPUEntityManager.createQuery("SELECT i FROM Interviews i");
        interviewsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : interviewsQuery.getResultList();
        addNewButton = new javax.swing.JButton();
        updateInterviewButton = new javax.swing.JButton();
        deleteInterviewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setAutoCreateRowSorter(true);

        setTitle("Interviews");

        addNewButton.setText("New");
        addNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        updateInterviewButton.setText("Edit");
        updateInterviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInterviewButtonActionPerformed(evt);
            }
        });

        deleteInterviewButton.setText("Delete");
        deleteInterviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInterviewButtonActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, interviewsList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${title}"));
        columnBinding.setColumnName("Title");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${informant}"));
        columnBinding.setColumnName("Informant");
        columnBinding.setColumnClass(spudrucket.github.io.Colloquium.Informants.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${interviewer}"));
        columnBinding.setColumnName("Interviewer");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${interviewdate}"));
        columnBinding.setColumnName("Interviewdate");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${location}"));
        columnBinding.setColumnName("Location");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${summary}"));
        columnBinding.setColumnName("Summary");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(10);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(2).setMinWidth(50);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(3).setMinWidth(50);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(4).setMinWidth(50);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(5).setMinWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addNewButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateInterviewButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInterviewButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewButton)
                    .addComponent(updateInterviewButton)
                    .addComponent(deleteInterviewButton))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Interviews getSelectedInterview () {
        Interviews selectedInterview = null;
        if (jTable1.isRowSelected(jTable1.getSelectedRow())) {
            for (Interviews i : interviewsList) {
                if (i.getId().equals(jTable1.getValueAt(jTable1.getSelectedRow(), idColumn))) {
                selectedInterview = i;
                break;
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null,"Please first select an Interview.");
        }
        return selectedInterview;
    }
    
    private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonActionPerformed
        AddInterview addint = new AddInterview(mainwindow);
        addint.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addNewButtonActionPerformed

    private void updateInterviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInterviewButtonActionPerformed
        if (getSelectedInterview() != null) {
            UpdateInterviews uint = new UpdateInterviews(getSelectedInterview(), mainwindow);
            uint.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_updateInterviewButtonActionPerformed

    private void deleteInterviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInterviewButtonActionPerformed
        if (getSelectedInterview() != null) {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this Interview? \n All interview data will be lost.");
            if (confirm == 0) {
                int interviewId = getSelectedInterview().getId();
                
                EntityManager entityManager = Persistence.createEntityManagerFactory("ColloquiumPU").createEntityManager();
                Query query = entityManager.createQuery("SELECT p.id FROM Paragraphs p WHERE p.interviewnumber.id = " + String.valueOf(interviewId));
                List<Integer> paragraphId = query.getResultList();
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("ColloquiumPU");
                ParagraphsJpaController pjc = new ParagraphsJpaController(emf);
                for (int i : paragraphId) {
                    try {
                        pjc.destroy(i);
                    } catch (NonexistentEntityException ex) {
                        Logger.getLogger(ShowInterviews.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalOrphanException ex) {
                        Logger.getLogger(ShowInterviews.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }                               
                InterviewsJpaController ijc = new InterviewsJpaController(emf);
                try {
                    ijc.destroy(interviewId);
                } catch (IllegalOrphanException ex) {
                    Logger.getLogger(ShowInterviews.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(ShowInterviews.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
                ShowInterviews sint = new ShowInterviews();
                sint.setVisible(true);
                mainwindow.populateTree();
            }            
        }
    }//GEN-LAST:event_deleteInterviewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ColloquiumPUEntityManager;
    private javax.swing.JButton addNewButton;
    private javax.swing.JButton deleteInterviewButton;
    private java.util.List<spudrucket.github.io.Colloquium.Interviews> interviewsList;
    private javax.persistence.Query interviewsQuery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updateInterviewButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
